/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AdminIndexRouteImport } from './routes/_admin.index'
import { Route as loginLayoutRouteImport } from './routes/(login)/_layout'
import { Route as loginLayoutZapomenuteHesloIndexRouteImport } from './routes/(login)/_layout/zapomenute-heslo/index'
import { Route as loginLayoutRegistraceIndexRouteImport } from './routes/(login)/_layout/registrace/index'
import { Route as loginLayoutLoginIndexRouteImport } from './routes/(login)/_layout/login/index'

const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const loginLayoutRoute = loginLayoutRouteImport.update({
  id: '/(login)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const loginLayoutZapomenuteHesloIndexRoute =
  loginLayoutZapomenuteHesloIndexRouteImport.update({
    id: '/zapomenute-heslo/',
    path: '/zapomenute-heslo/',
    getParentRoute: () => loginLayoutRoute,
  } as any)
const loginLayoutRegistraceIndexRoute =
  loginLayoutRegistraceIndexRouteImport.update({
    id: '/registrace/',
    path: '/registrace/',
    getParentRoute: () => loginLayoutRoute,
  } as any)
const loginLayoutLoginIndexRoute = loginLayoutLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => loginLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/login': typeof loginLayoutLoginIndexRoute
  '/registrace': typeof loginLayoutRegistraceIndexRoute
  '/zapomenute-heslo': typeof loginLayoutZapomenuteHesloIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AdminIndexRoute
  '/login': typeof loginLayoutLoginIndexRoute
  '/registrace': typeof loginLayoutRegistraceIndexRoute
  '/zapomenute-heslo': typeof loginLayoutZapomenuteHesloIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/(login)/_layout': typeof loginLayoutRouteWithChildren
  '/_admin/': typeof AdminIndexRoute
  '/(login)/_layout/login/': typeof loginLayoutLoginIndexRoute
  '/(login)/_layout/registrace/': typeof loginLayoutRegistraceIndexRoute
  '/(login)/_layout/zapomenute-heslo/': typeof loginLayoutZapomenuteHesloIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/registrace' | '/zapomenute-heslo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/registrace' | '/zapomenute-heslo'
  id:
    | '__root__'
    | '/_admin'
    | '/(login)/_layout'
    | '/_admin/'
    | '/(login)/_layout/login/'
    | '/(login)/_layout/registrace/'
    | '/(login)/_layout/zapomenute-heslo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  loginLayoutRoute: typeof loginLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/(login)/_layout': {
      id: '/(login)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof loginLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(login)/_layout/zapomenute-heslo/': {
      id: '/(login)/_layout/zapomenute-heslo/'
      path: '/zapomenute-heslo'
      fullPath: '/zapomenute-heslo'
      preLoaderRoute: typeof loginLayoutZapomenuteHesloIndexRouteImport
      parentRoute: typeof loginLayoutRoute
    }
    '/(login)/_layout/registrace/': {
      id: '/(login)/_layout/registrace/'
      path: '/registrace'
      fullPath: '/registrace'
      preLoaderRoute: typeof loginLayoutRegistraceIndexRouteImport
      parentRoute: typeof loginLayoutRoute
    }
    '/(login)/_layout/login/': {
      id: '/(login)/_layout/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof loginLayoutLoginIndexRouteImport
      parentRoute: typeof loginLayoutRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface loginLayoutRouteChildren {
  loginLayoutLoginIndexRoute: typeof loginLayoutLoginIndexRoute
  loginLayoutRegistraceIndexRoute: typeof loginLayoutRegistraceIndexRoute
  loginLayoutZapomenuteHesloIndexRoute: typeof loginLayoutZapomenuteHesloIndexRoute
}

const loginLayoutRouteChildren: loginLayoutRouteChildren = {
  loginLayoutLoginIndexRoute: loginLayoutLoginIndexRoute,
  loginLayoutRegistraceIndexRoute: loginLayoutRegistraceIndexRoute,
  loginLayoutZapomenuteHesloIndexRoute: loginLayoutZapomenuteHesloIndexRoute,
}

const loginLayoutRouteWithChildren = loginLayoutRoute._addFileChildren(
  loginLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  loginLayoutRoute: loginLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
